classes/urls.py
from django.conf.urls import url
from classes.views import ClassListView
app_name = 'classes'
urlpatterns = [
	url('',ClassListView.as_view(),name="class_list"),

]

public_app/urls.py
from django.conf.urls import url
from public_app.views import HomeView


urlpatterns = [
    url('', HomeView.as_view()),
]

student_management/urls.py
from django.conf.urls import include,url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'^students/', include('students.urls',namespace="students")),
   	url(r'^classes/', include('classes.urls',namespace="classes")),
   	url(r'^teacher/', include('teachers.urls',namespace="teachers")),
    url('', include('public_app.urls')),

]

students/urls.py
from django.conf.urls import url
from students.views import StudentListView

app_name = 'students'
urlpatterns = [
	url(r'^(?P<pk>[0-9]+)/$',StudentListView.as_view(),name="student_list"),





]

teachers/urls.py
from django.conf.urls import url
from teachers.views import LoginView, DashboardView,LogoutView,PasswordView


app_name = 'teachers'
urlpatterns = [
	url(r'^reset/$', PasswordView.as_view(), name="passwordreset"),
	url(r'^logout/$', LogoutView.as_view(), name="logout"),
	url(r'^login/$',LoginView.as_view(),name="login_page"),
	url(r'^dashboard/$',DashboardView.as_view(), name="dashboard"),




]

classes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Classes(models.Model):
	name = models.CharField(null=False,blank=False,max_length=15)

	def __str__(self):
		return self.name

public_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

students/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from classes.models import Classes


class Students(models.Model):
	name = models.CharField(null=False,blank=False,max_length=40)
	roll_no = models.PositiveIntegerField() 
	age =  models.PositiveIntegerField()
	student_class = models.ForeignKey(Classes,on_delete=models.DO_NOTHING, related_name="students")

	def __str__(self):
		return self.name
		
		

teachers/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from classes.models import Classes

# Create your models here.

class TeacherClasses( models.Model):
	teacher = models.ForeignKey(User, on_delete=models.DO_NOTHING)
	teacher_class = models.ForeignKey(Classes, on_delete=models.DO_NOTHING)

	def __str__(self):
		return self.teacher.username


	

classes/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views.generic.list import ListView
from classes.models import Classes


# Create your views here.
class ClassListView(ListView):
	template_name ="classes/classes_list.html"
	model = Classes




	"""docstring for ClassListView"""
	

public_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.generic.base import TemplateView
from django.shortcuts import render
from classes.models import Classes
from students.models import Students
from teachers.models import TeacherClasses
from django.contrib.auth.models import User


# Create your views here.
class HomeView(TemplateView):
	"""docstring for HomeView"""

	template_name = "common/base.html"
	model = Classes

	
	def get_context_data(self, **kwargs):
		s_total = Students.objects.all().count()
		# t_total = User.objects.all().count()
		a  =  User.objects.filter(is_superuser=False).count()
		# count = Classes.objects.all()
		context = super(HomeView, self).get_context_data(**kwargs)
		context['total_students'] = s_total
		context['total_teachers'] =  a

		# context['classes'] = count
		return context
		

students/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views.generic.detail import DetailView
from classes.models import Classes


class StudentListView(DetailView):
	"""docstring for ClassName"""

	template_name = "students/student_list.html"
	model = Classes

















# from django.shortcuts import render
# from django.views.generic.list import ListView
# from  students.models import  Students

# # Create your views here.
# class StudentListView(ListView):
# 	template_name = "students/student_list.html"
# 	model = Students
	
		

teachers/views.py
from __future__ import unicode_literals
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import View
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from teachers.models import TeacherClasses
from django.contrib.auth.models import User
# Create your views here.


class DashboardView(LoginRequiredMixin, TemplateView):
	template_name = 'teachers/dashboard.html'
	login_url = '/teacher/login/'

	def get_context_data(self, **kwargs):
		context = super(DashboardView, self).get_context_data(**kwargs)
		teacher = self.request.user
		teachersclassesObjects = TeacherClasses.objects.filter(teacher = teacher)
		context['teacher_classes'] = teachersclassesObjects


		return context


class LoginView(View): 

	template_name = 'teachers/login.html'

	def get(self, request, *args, **kwargs):
		return render(request, self.template_name)

	def post(self, request, *args, **kwargs):
		username = request.POST.get('username', None)
		password = request.POST.get('password', None)

		user = authenticate(request, username=username, password=password)
		if user is not None:
			if  user==User.objects.filter(is_superuser=False):
				login(request, user)
				link = reverse('teachers:dashboard')
				return redirect(link)
			else:
				return render(request, self.template_name, {"msg": "Invalid Credentials"})


class LogoutView(View): 

	def get(self, request, *args, **kwargs):
		logout(request)
		link = reverse('teachers:login_page')
		return redirect(link)

class PasswordView(View):
	template_name = 'teachers/resetpassword.html'
	
	def get(self, request, *args, **kwargs):
		return render(request, self.template_name)
		

classes/templates/classes/classes_list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<table>
		<tr>
			<th>Id</th>
			<th>Class_Name</th>
		</tr>
{% for class in object_list %}
		<tr>
			<td>{{class.id}}</td>
			<td>{{class.name}}</td>
	</tr>
{% endfor %}
	
</table>

public_app/templates/common/base.html
{% load common_tags %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
<html>
	<head>
		<body>

			{% block  'head_section' %}
			<div class="main">
				<!-- main div starts -->
				<header class="page-header">
					<!-- page header starts -->
					<div class="logodiv">
						<a href=""><img src="{% static 'images/logo.png' %}"  alt="Smiley face" class="logo"></a>
					</div>
					<!-- logo div closed -->
					<div class="schoolname">
						<p>Delhi Public School</p>
						
					</div>
					<div class="login">
						<ul>
							<li><a href="http://127.0.0.1:8000/teacher/login/">Login</a></li>
						</ul>
					</div>
					<!-- login div closed -->
					<div class="nav">
						<ul>
							<li><a href="">Home</a></li>
							<div class="dropdown">
								<li><a href="" class="dropbtn">Class</a></li>
								<div class="dropdown-content">
								    {% class_list %}

								    
								</div>
							</div>
							<li><a href="">Contact</a></li>
						</ul>
					</div>

				</header>
				{% endblock %}
				
				
				<div class="content">
					<div class="totalstudents">TOTAL STUDENTS
						{{total_students}}{{total_teachers}}
						
					</div>
					<div class="totalstudents">TOTAL TEACHERS
						{{total_teachers}}
						
					</div>
					
					<p>There are a wide range of Indian vegetables that you can find in the market that you will need. Be it your green vegetables, fiber rich vegetables, exotic vegetables or any green leafy vegetables, you can find it on bigbasket</p>
					<p>There are a wide range of Indian vegetables that you can find in the market that you will need. Be it your green vegetables, fiber rich vegetables, exotic vegetables or any green leafy vegetables, you can find it on bigbasket</p>
					<p>There are a wide range of Indian vegetables that you can find in the market that you will need. Be it your green vegetables, fiber rich vegetables, exotic vegetables or any green leafy vegetables, you can find it on bigbasket</p>
					<p>There are a wide range of Indian vegetables that you can find in the market that you will need. Be it your green vegetables, fiber rich vegetables, exotic vegetables or any green leafy vegetables, you can find it on bigbasket</p>
					<p>There are a wide range of Indian vegetables that you can find in the market that you will need. Be it your green vegetables, fiber rich vegetables, exotic vegetables or any green leafy vegetables, you can find it on bigbasket</p>
						}

				</div>
				<h3 style="text-align:center"></h3>
				<li>
				</div>
				<!-- page header closed -->
				<div class="push"></div>
				<footer>copyright@2020</footer>

			</div>
			<!-- main div closed -->
		</body>
	</head>
</html>

public_app/templates/common/footer.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
<html>
	<head>
		<body>

			
			
			
				<!-- page header closed -->
				<div class="push"></div>
				<footer>{{total_students}}</footer>
				

			
			<!-- main div closed -->
			
		</body>
	</head>
</html>

public_app/templates/common/header.html
{% load common_tags %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
<html>
	<head>
		<body class="headerbody">

			

			
				<!-- main div starts -->
				<header class="page-header">
					<!-- page header starts -->
					<div class="logodiv">
						<a href=""><img src="{% static 'images/logo.png' %}"  alt="Smiley face" class="logo"></a>
					</div>
					<!-- logo div closed -->
					<div class="schoolname">
						<p>Delhi Public School</p>
						
					</div>
					<div class="login">
						<ul>
							{% if user.is_authenticated %}
					<li class="leftalign"><a href="{% url 'teachers:logout' %}">Logout</a></li>
					<li class="leftalign"><a href="{% url 'teachers:dashboard' %}">Dashboard</a></li>
					<li class="leftalign"><a href="{% url 'teachers:passwordreset' %}">My account</a></li>
				{% else %}
					<li class="leftalign"><a href="{% url 'teachers:login_page' %}">Login</a></li>
				{% endif %}
							<!-- <li><a href="http://127.0.0.1:8000/teacher/login/">Login</a></li> -->
						</ul>
					</div>
					<!-- login div closed -->
					<div class="nav">
						<ul>
							<li><a href="http://127.0.0.1:8000/">Home</a></li>
							<div class="dropdown">
								<li><a href="" class="dropbtn">Class</a></li>
								<div class="dropdown-content">
								    
									 
									{% class_list %}

									

								    
								</div>
							</div>
							<li><a href="">Contact</a></li>
						<!-- 	{% if user.is_authenticated %}
					<li class="leftalign"><a href="{% url 'teachers:logout' %}">Logout</a></li>
					<li class="leftalign"><a href="{% url 'teachers:dashboard' %}">Dashboard</a></li>
					<li class="leftalign"><a href="{% url 'teachers:passwordreset' %}">My account</a></li>
				{% else %}
					<li class="leftalign"><a href="{% url 'teachers:login_page' %}">Login</a></li>
				{% endif %} -->
						</ul>
					</div>

				</header>
				
				
				
			<!-- main div closed -->
		</body>
	</head>
</html>

students/templates/students/student_list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
{% include "common/header.html" %}

<!-- {% for class in object_list %}
	<table>
		<tr>
			<td>{{class.id}}</td>
			<td>{{class.name}}</td>
		</tr>
</table>
{% endfor %} -->

<h1>{{ object.name }} - {{ object.id }}</h1>
		
<table>
	
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Age</th>
			<th>Roll No</th>
			<th>Class Name</th>
			{% if user.is_authenticated %}
			<th>Action</th>		
				{% endif %}
		</tr>
	
	
		
		{% for student in object.students.all %}
			<tr>
				<td>{{ student.id }}</td>
				<td>{{ student.name }}</td>
				<td>{{ student.age }}</td>
				<td>{{ student.roll_no }}</td>
				<td>{{ student.student_class.name }}</td>
				{% if user.is_authenticated %}
					<td><a href="#">Edit</a> | <a href="#">Delete</a> </td>		
				{% endif %}
			</tr>
		{% endfor %}

		<!-- {% for student in object_list %}
		<tv
		{% endfor %} -->
	
</table>
{% include "common/footer.html" %}

teachers/templates/teachers/dashboard.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
{% include "common/header.html" %}

<!-- {% for class in object_list %}
	<table>
		<tr>
			<td>{{class.id}}</td>
			<td>{{class.name}}</td>
		</tr>
</table>
{% endfor %} -->

<h1>{{ object.name }} - {{ object.id }}</h1>
		
<table>
	
		<tr>
			<th>Class Name</th>
			<th>Student Total</th>
			<th>Action</th>
		</tr>
	
	{% for  cls in teacher_classes %}
				<tr>
					<td>{{ cls.teacher_class.name}}</td>
					<td>{{ cls.teacher_class.students.count }}</td>
					<td><a href="{% url 'students:student_list' cls.teacher_class.id%}">view details</td>
				</tr>
			{% endfor %}
<!-- {% url 'teachers:login_page' %} -->
		
		<!-- {% for student in object.students.all %}
			<tr>
				<td>{{ student.id }}</td>
				<td>{{ student.name }}</td>
				<td>{{ student.age }}</td>
				<td>{{ student.roll_no }}</td>
				<td>{{ student.student_class.name }}</td>
			</tr>
		{% endfor %} -->

		<!-- {% for student in object_list %}
		<tv
		{% endfor %} -->
	
</table>
{% include "common/footer.html" %}

teachers/templates/teachers/login.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
{% include "common/header.html" %}
<div class="otrdiv">
<div class="formstyle">
<form name="emp" action="{% url 'teachers:login_page' %}" method="post">{% csrf_token %}
	 <label for="email">Username</label><br>
	<input type="text" name="username" required placeholder="enter username  "><br>
	<label for="password">password</label><br>
	<input type="password" name="password" required placeholder="enter password"><br>
	<input type="checkbox">Remember me<br>
	<input type="submit" name="btn" value="Login" class="btn">
	{% if msg %}
	<p>{{ msg }}</p>
{% endif %}
	
</form>
</div>
</div>
{% include "common/footer.html" %}

teachers/templates/teachers/resetpassword.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
{% include "common/header.html" %}
<div class="otrdiv">
<div class="formstyle">
<form name="emp" action="{% url 'teachers:passwordreset' %}" method="post">{% csrf_token %}
	<label for="password">Current password</label><br>
	<input type="password" name="c_password" required placeholder="enter password"><br>
	<label for="password">New password</label><br>
	<input type="password" name="n_password" required placeholder="enter password"><br>
	<label for="password">confirm password</label><br>
	<input type="password" name="v_password" required placeholder="enter password"><br>
	
	<input type="submit" name="btn" value="Login" class="btn">
	{% if msg %}
	<p>{{ msg }}</p>
{% endif %}
	
</form>
</div>
</div>
{% include "common/footer.html" %}